version: '2'
services:
  db_data:
    image: busybox
    volumes:
      - /var/lib/mysql
  db:
    image: mysql:5.7
    platform: linux/x86_64
    volumes_from:
      - db_data
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: nest-prisma
      MYSQL_ROOT_PASSWORD: password
